### ISSUE TITLE
Docs: update DG

### ISSUE THREAD

**Issue by jasonqiu212** [AY2223S1-CS2103T-T12-2/tp#236]
## Tasks
- [x] Add line break after section
- [x] Edit section headings
- [x] Remove find_task implementation explanation
- [x] Add optional fields implementation explanation
- [x] Update UML images
