### ISSUE TITLE
Update UG

### ISSUE THREAD

**Issue by jasonqiu212** [AY2223S1-CS2103T-T12-2/tp#259]
## Tasks
- [x] Update feature summary in about us section
- [x] Check wording
- [x] Check heading capitalizations
- [x] Replace all John Does
- [x] Use more 'you' language?
- [x] Add preface for command summary to mention it's ordered alphabetically
