### ISSUE TITLE
Update developer guide

### ISSUE THREAD

**Issue by jasonqiu212** [AY2223S1-CS2103T-T12-2/tp#6]
## Tasks
- Add following to DG:
    - Target user profile, value proposition, user stories
    - Use cases
    - NFRs
    - Glossary

[Link](https://nus-cs2103-ay2223s1.github.io/website/schedule/week7/project.html#5-update-the-dg-user-stories-glossary-nfrs-use-cases) to details

### Team checklist
- [ ] Santosh: NFRs
- [ ] Yun Ru: Glossary
- [ ] Pep: Use cases
- [ ] Jason: Target user profile, value proposition, user stories
